### ISSUE TITLE
Get bounds updates onto Hackage

### ISSUE THREAD

**Issue by chris-martin** [Profpatsch/libnix-haskell#6]
https://github.com/Profpatsch/libnix-haskell/pull/3 needs a new release, but https://github.com/Profpatsch/libnix-haskell/pull/5 could be accomplished just with a metadata revision. Might you consider adding a maintainer to help get these out promptly?

**Comment by Profpatsch** [comment]
Hi, I added you to the maintainer list and invited you to this repository. Thank you for being interested in co-maintainership.
